database:
    name: "database_name"
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "your_password"

handler:
    api_version: "1.0"
    port: ":8080"

platform:
    url: "platform_url"
    ssl_path_pem: "./ssl/apikey.pem"
    ssl_path_key: "./ssl/client.key"